/* jshint -W014, -W033, esversion: 9 */
/* eslint-disable new-cap */
'use strict'

module.exports = {
  cantReadPacket: 'LAN message received could not be read as',
  cantParsePacket: 'Could not parse DNS packet as',
  cfgDef: 'is not a valid number so using default of',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  complete: '✓ Setup complete',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised and',
  devInitOpts: 'initialising with options',
  devNewNotAdd: 'restart Homebridge to add new device, failed to add automatically as',
  devNoAPIKey: 'cannot retrieve device API key',
  devNoControl: 'cannot be controlled as mode:lan is not compatible with this device',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotConfLAN: 'device/command not available via LAN mode',
  devNotFound: 'device not found in eWeLink',
  devNotInit: 'could not be initialised as',
  devNotReachLAN: 'device not reachable via LAN mode',
  devNotRf: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devNotSup: 'has not been added as it cannot be supported',
  devNotSupYet: 'is not supported, please make a GitHub issue with the following info',
  devNotUpd: 'device update failed as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disabling: 'Disabling plugin',
  errGetDevice: 'An error occurred during http getDevice()',
  errGetDevices: 'An error occurred during http getDevices()',
  errGetHost: 'An error occurred during ws getHost()',
  errLogin: 'An error occurred during http login()',
  eweError: 'An eWeLink error [500] occured, retrying in 30 seconds',
  foundWithIP: 'found locally with IP',
  httpRetry: 'Unable to reach eWeLink, retrying in 30 seconds',
  identify: 'identify button pressed',
  initialised: 'initialised. Syncing with eWeLink',
  lanDisabled: 'LAN mode is disabled',
  lanErr: 'unknown LAN error',
  lanMonitor: 'LAN monitoring started',
  lanNotSup: 'LAN mode is not supported for sending updates to this device',
  lanStarted: 'LAN discovery complete',
  lanStarting: 'LAN discovery starting',
  lanUnreachable: 'LAN mode unavailable as unreachable',
  lanUnsupported: 'LAN mode unavailable as not supported',
  missingCreds: 'eWeLink credentials missing from configuration',
  missingPW: 'eWeLink password missing from configuration',
  missingUN: 'eWeLink username missing from configuration',
  newRegionRec: 'New HTTP API host received',
  noAuthRec: 'No auth token received',
  noRegionRec: 'No valid region received',
  noWSHost: 'Server did not respond with a web socket host',
  recNew: 'receiving update for new device',
  repOffline: 'reported [offline]',
  repOnline: 'reported [online]',
  revertWS: 'reverting to web socket as',
  sendLogin: 'Sending HTTP login() request',
  sonoffCamera: 'see the homebridge-ewelink wiki for details to enable the camera',
  stoppedLAN: 'LAN monitoring gracefully stopped',
  stoppedWS: 'Web socket gracefully closed',
  unreachable: 'it is unreachable',
  updRec: 'receiving update',
  updReq: 'requesting current status',
  updSend: 'sending update',
  viaLAN: 'via LAN',
  viaWS: 'via WS',
  wsHostRec: 'Web socket host received',
  wsLogin: 'Sending WS login request',
  wsLoginErr: 'Unknown WS parameters received',
  wsLoginError: 'WS login failed as',
  wsLoginErrRecon: 'WS could not be opened and will try again in 5 seconds',
  wsLoginSuccess: 'WS login successful',
  wsLogin406: 'WS login failed [406] please see http://bit.ly/hb-ewelink-errors',
  wsPingError: 'Cound not send WS ping as',
  wsRec: 'WS message received',
  wsReconnectClose: 'WS close event and will try to reconnect in 5 seconds',
  wsReconnectError: 'WS error event and will try to reconnect in 5 seconds',
  wsRef: 'Refreshing WS connection',
  wsRefFail: 'Refreshing WS connection failed as',
  wsRequired: 'update must be sent this way',
  wsReqTimeout: 'request timeout',
  wsResend: 'Request will be sent when WS has reconnected',
  wsUnkAct: 'WS message received has unknown action',
  wsUnkCmd: 'WS unknown command received',
  wsUnkRes: 'unknown WS response',
  zWelcome: [
    "Don't forget to ☆ this plugin on GitHub if you're finding it useful!",
    'Have a feature request? Visit http://bit.ly/hb-ewelink-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    "Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW",
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Have time to give this plugin a review? http://bit.ly/hb-ewelink-review',
    'Want to see this plugin in your own language? Let me know!'
  ]
}
