export default {
  apiListenErr: 'Erreur de serveur d\'API interne',
  apiListening: 'API interne à l\'écoute sur le port',
  apiShutdown: 'L\'API interne s\'arrête normalement',
  beta: 'You are using a beta version of the plugin - you will experience more logging than normal',
  buttonDouble: 'appui double',
  buttonLong: 'appui long',
  buttonNotFound: 'rf button non trouvé (veuillez redémarrer Homebridge)',
  buttonSingle: 'appui simple',
  buttonTrig: 'boutton déclenché',
  cantReadPacket: 'Le message LAN reçu n\'a pas pu être lu comme',
  cantParsePacket: 'Impossible d\'analyser le paquet DNS en tant que',
  cfgDef: 'n\'est pas un nombre valide, utilisation de la valeur par defaut',
  cfgDup: 'sera ignoré tant qu\'une autre entrée avec cet ID existe',
  cfgIgn: 'ignoré car non configuré correctement',
  cfgIgnItem: 'a une entrée invalide et sera ignoré',
  cfgItem: 'Configurer l\'entrée',
  cfgLow: 'à une valeur trop basse et sera augmenté à',
  cfgRmv: 'n\'est pas utilisé et peut-être enlevé',
  cfgQts: 'ne devrait pas avoir de guillemets autour de son entrée',
  complete: '✓ Configuration complète',
  contactNo: 'contact non detecté',
  contactYes: 'contact detecté',
  curBatt: 'batterie actuelle',
  curBright: 'luminosité actuelle',
  curColour: 'couleur actuelle',
  curCool: 'refroidissement actuel',
  curCurr: 'actuel actuel',
  curDehumid: 'déshumidification actuelle',
  curHeat: 'chauffage actuel',
  curHumi: 'humidité actuelle',
  curHumid: 'humidification actuelle',
  curLight: 'lumière actuelle',
  curMode: 'mode actuel',
  curPos: 'position actuelle',
  curPower: 'alimentation actuelle',
  curPur: 'purification actuelle',
  curScene: 'current scene',
  curSpeed: 'vitesse actuelle',
  curState: 'état actuel',
  curTarg: 'cible actuelle',
  curTemp: 'température actuelle',
  curVolt: 'voltage actuel',
  devAdd: 'a été ajouté à Homebridge',
  devInit: 'initialisé et',
  devInitGroup: 'initialised with group id',
  devInitOpts: 'initialisation avec options',
  devNewNotAdd:
    'redémarrer Homebridge pour ajouter un nouvel appareil, echec de l\'ajout automatique en tant que',
  devNoAPIKey: 'ne peux pas récupérer la clé API de l\'appareil',
  devNoControl: 'ne peux pas être controlé via le mode:lan n\'est pas compatible avec ce device',
  devNotAdd: 'ne peux pas être ajouté à Homebridge en tant que',
  devNotConf: 'ne peux pas être configuré en tant que ',
  devNotConfLAN: 'appareil/commande non disponible via le mode LAN',
  devNotFound: 'appareil non trouvé dans eWeLink',
  devNotInit: 'ne peux pas être intialisé en tant que',
  devNotReachLAN: 'appareil non joignable via le mode LAN',
  devNotRf: 'ne peux pas être raffraichi en tant que',
  devNotRemove: 'ne peux pas être supprimé de Homebridge en tant que',
  devNotSup: 'n\'a pas pus être ajouté car ne peux pas être pas supporté',
  devNotSupYet: 'non supporté, crée un ticket incident sur Github avec les infos suivantes',
  devNotUpd: 'echec de la mise à jour de l\'appareil en tant que',
  devRemove: 'a été supprimé de Homebridge',
  disabledAL: 'luminosité adaptative désactivée suite à un changement de couleur',
  disabling: 'Désactivation du plugin',
  doorClosed: 'fermée',
  doorOpen: 'ouverte',
  dualr3NoCalib: 'Doit être calibré pour fonctionner en mode moteur',
  dualr3NoMeter: 'n\'est pas supporté en mode mètre',
  errGetDevices: 'Une erreur est survenue durant https getDevices()',
  errGetHost: 'Une erreur est survenue durant ws getHost()',
  errLogin: 'Une erreur est survenue durant http login()',
  eweError: 'Une erreur eWeLink [500] est survenue, nouvel essaie dans 30 secondes',
  fetchHome: 'Fetching devices from eWeLink home/id',
  foundWithIP: 'trouvé locallement avec IP',
  foundWithManIP: 'utilisation de l\'IP manuelle',
  hbVersionFail: 'Votre version de Homebridge est trop ancienne - Mettez à jour vers v1.6',
  heaterSimNoSensor: 'you must configure a device ID that provides a temperature reading',
  httpDisabled: 'HTTP/WS clients désactivé en tant que',
  httpLogin10003:
    'Consulter https://bit.ly/hb-ewelink-errors pour plus d\'informations sur cette erreur de connexion',
  httpRetry: 'eWelink n\'est pas joignable, réessai dans 30 secondes',
  identify: 'identifier le bouton préssé',
  initialised: 'Plugin intitialisé. Configuration des accessoires...',
  initialising: 'Initialisation du plugin',
  invalidConfig: 'Configuration invalide',
  lanDisabled: 'LAN mode est désactivé',
  lanErr: 'Error LAN inconnue',
  lanIPDifferent: 'IP manuelle ignorée depuis la découverte d\'une IP différente',
  lanMonitor: 'Surveillance LAN démarré',
  lanNotSup: 'le mode LAN n\'est pas supporté pour envoyer des mise à jour vers cet appareil',
  lanStarted: 'Découverte LAN complète',
  lanStarting: 'Début de la découverte LAN',
  lanUnsupported: 'le mode LAN est indisponible car il est indisponible ou non découvert',
  leakNo: 'fuite non détectée',
  leakYes: 'fuite detectée',
  lockLocked: 'Vérouillé',
  lockUnlocked: 'Déverouillé',
  missingCreds: 'paramètres de connexion eWeLink non configurés',
  motionNo: 'mouvement non detecté',
  motionYes: 'mouvement detecté',
  newIP: 'changement de l\'adresse IP pour',
  newRegionRec: 'Nouvel API hôte HTTTP reçcus',
  noAuthRec: 'pas de token d\'authentification reçus',
  noGarageForOD: 'pas daccessoire de porte de garage trouvé',
  noRegionRec: 'pas de région valide reçus',
  noWSHost: 'le serveur ne répond pas avec un hote web socket',
  occupancyNo: 'occupancy not detected',
  occupancyYes: 'occupancy detected',
  pluginNotConf: 'le plugin n\'a pas été configuré',
  repOffline: 'a été rapporté [offline]',
  repOnline: 'a été rapporté [online]',
  revertWS: 'retour au web socket en tant que',
  rfNotFound: 'essayez de redémarrer Homebridge car aucun accéssoires n\'a été trouvé pour',
  rfTrigNo: 'non déclenché',
  rfTrigYes: 'déclenché',
  sendLogin: 'Envoie d\'une requete HTTP login()',
  sensorErr:
    'non supporté comme des/humidifier tant que l\'équipement n\'à pas de capteur pris en charge',
  sensorNo: 'désactivé',
  sensorYes: 'activé',
  sensorNoDevice: 'garage/lock accessory not found, this device will be setup as a normal sensor',
  shareWarn:
    'utiliser un équipement partagé avec le cloud peut provoquer des erreurs, utilisez votre compte eWelink principal',
  smokeNo: 'smoke not detected',
  smokeYes: 'smoke detected',
  sonoffCamera: 'voir le wiki homebridge-ewelink pour plus de détails sur l\'activation de caméra',
  stoppedLAN: 'surveillance LAN gracieusement arreté',
  stoppedWS: 'socket web fracieusement fermé',
  storageClearErr: 'Ne peut pas vider le stockage du dossier en tant que',
  storageReadErr: 'Ne peut pas lire le dossier persitat en tant que',
  storageSetupErr: 'Ne peut pas paramétrer le stockage client en tant que',
  storageWriteErr: 'ne peux pas sauvegarder l\'équipement dans un fichier en tant que',
  unreachable: 'n\'est pas joignable',
  updRec: 'reception d\'une mise à jour',
  updReq: 'récupération de l\'état actuel',
  updSend: 'envoie de la mise à jour',
  valveNo: 'arreté',
  valveYes: 'en fonctionnement',
  viaAL: 'via éclairafe adaptatif',
  viaLAN: 'via LAN',
  viaWS: 'via WS',
  welcome: 'Ce plugin a été fait avec ♥ par bwp91, n\'oubliez pas de ☆ ce plugin sur GitHub si vous le trouvez utile!',
  wsHostRec: 'reception d\'un hôte Web socket',
  wsLogin: 'Envoie d\'une requête de connection WS',
  wsLoginErr: 'Paramètres WS reçus inconnus',
  wsLoginError: 'Echec de la connection WS en tant que',
  wsLoginErrRecon: 'WS n\'a pas pus être ouvert and réessaiera dans 5 secondes',
  wsLoginSuccess: 'Succès de la connection WS',
  wsLogin406: 'Echec de la connection WS [406] voir https://bit.ly/hb-ewelink-errors',
  wsPingError: 'Ne peux pas envoyer un ping WS en tant que',
  wsRec: 'Message WS reçus',
  wsReconnectClose: 'Évènement de fermeture WS et réessaiera de se connecter dans 5 secondes',
  wsReconnectError: 'Évènement d\'erreur WS et réessaiera de se connecter dans 5 secondes',
  wsRef: 'Actualisation de la connection WS',
  wsRefFail: 'Echec de l\'actualisation de la connection en tant que',
  wsRequired: 'la mise à jour doit être envoyée de cette façon',
  wsReqTimeout: 'demande de délai d\'attente',
  wsResend: 'Web socket n\'est pas ouvert - réessayer dans quelques secondes',
  wsUnkAct: 'message WS reçus comme action inconnue',
  wsUnkCmd: 'commande WS inconnue reçue',
  wsUnkRes: 'réponse WS inconnue reçue',
};
